name: Run Python Script Monthly

on:
  schedule:
    - cron: "0 12 24 * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    
    env:
      REDIS_URI: ${{ secrets.REDIS_URI }} 
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run script
        run: python rpa_noticias.py